### ISSUE TITLE
VSCode is not detected 

### ISSUE THREAD

**Issue by jshederer** [docker/dev-environments#27]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:73CF25EE-6654-41BA-918C-DBE649F7E4B2/20210710203913

### Actual behavior
In "Dev Environments", neither Visual Studio Code nor Visual Studio Code Remote Containers Extension are detected. 
Visual Studio perfectly sees containers. I'm able to start a container from Visual Studio. 
I've restarted Docker desktop 2 times. Uninstalled Visual Studio as user and installed as system. All without success. It is always not seend by Docker Desktop.

### Information

  - Windows Version: W10
  - Docker Desktop Version: last one
  - WSL2 or Hyper-V backend?  WSL2 activated
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no, on my PC

**Comment by hingston** [comment]
I was having the same issue. It was fixed in Docker Desktop version 3.5.2 (66501) for me.

**Comment by glours** [comment]
@jshederer we released a new version of Docker Desktop with some improvements on detecting prerequisites, can you upgrade your Docker Desktop by clicking on the `Check for Updates` menu and check that your problem is gone?

**Comment by carsoni** [comment]
Just upgraded to 3.6 but still seeing this problem. 

VSCode is installed. 
The appropriate extension is installed. 
I can successfully attach to the running dev environment container from my VSCode instance.

But Docker Desktop is still saying that I need to install VSCode and the Extension when I try to "Open in VSCode" from DD

**Comment by carsoni** [comment]
Adding to my previous comment.

I have now got the "Open in VSCode" feature working.

I performed the following 

- Deregistered the docker entries from the wsl subsystem

    To see what's there. I got docker-desktop and docker-desktop-data (I killed both of them)
        `wsl -l -v `
        `wsl --unregister docker-desktop`
        `wsl --unregister docker-desktop-data`

- Quit docker desktop from the SystemTray menu
- Stopped and restarted the docker service from the Services App
- Reinstalled VSCode ensuring I checked the "Write to PATH" option
- Restarted Docker Desktop
- Added a single container dev environment
- Waited for it to boot up
- Used the Open in VSCode button
- Success! :-)

**Comment by glours** [comment]
Hello @carsoni ,

Can we close this issue?

**Comment by carsoni** [comment]
Please take note of the second paragraph in my previous comment. 

I solved the issue and wrote in a comment the exact steps which solved it. 

Hopefully they will be useful to others. 

Please do close the issue but let’s leave the thread in place.
