### ISSUE TITLE
Requirements are not detected

### ISSUE THREAD

**Issue by slecache** [docker/dev-environments#5]
**Describe the bug**
Git, VSCode and VCode Remote Containers are installed but not detected.

I clicked on Retry, updated Git, updated VSCode, restarted Docker Desktop for Windows and restarted Windows but dependencies are still not detected.

**Screenshots**

![image](https://user-images.githubusercontent.com/9013641/123339283-93dd9280-d54a-11eb-81eb-f93f39a51366.png)

**Comment by nebuk89** [comment]
Hey @slecache, thanks for taking the time! Sorry it has gone odd :( 

Can you please close the UI, reopen it and then follow the instructions here to upload a diagnostics report: https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback

Please then post the ID here
🙏 thank you!

**Comment by rwood112** [comment]
I have the exact same issue, except that Git was initially detected as installed, and I needed to install the other two. After installing VS Code and the containers extension, Docker Desktop does not detect that they have been installed since the initial check. Diagnostic ID is: 
F4EB9DE1-8043-435C-A1B5-CA7135D60ED1/20210625184148

**Comment by mikaelkaron** [comment]
Same issue, Diagnostic ID: 2E7566C6-E2E0-4199-AA92-8033792CAEF6/20210626150820

**Comment by slecache** [comment]
Hi @nebuk89,

My diagnostic ID is 9E325B8A-9FD2-4067-82DB-93BD3A9FE810/20210626215749.

Let me know if you need more info or if you want me to do some testing.

Thanks for your help!

**Comment by rumpl** [comment]
Hey all, thank you for all the diagnostic ids, could you also provide us with the output of these lines:

```
$ which git
$ which code
```

Thanks!

**Comment by slecache** [comment]
From Git Bash :

```
$ which git
/mingw64/bin/git
$ which code
/c/Program Files/Microsoft VS Code/bin/code
```

From WSL :
```
$ which git
/usr/bin/git
$ which code
/mnt/c/Program Files/Microsoft VS Code/bin/code
```

**Comment by glours** [comment]
Few others questions for you all @slecache @mikaelkaron @rwood112:

- Did you add the`code` command line in Path?
- Are you using WSL2?
- Can you tell me if the following registry key `SOFTWARE\Classes\VSCodeSourceFile\shell\open`  is located in `HKEY_LOCAL_MACHINE` or `HKEY_USERS`/`HKEY_CURRENT_USER`?

**Comment by slecache** [comment]
> 
> 
> Few others questions for you all @slecache @mikaelkaron @rwood112:
> 
>     * Did you add the`code` [command line](https://code.visualstudio.com/docs/editor/command-line) in your Path?
The `/c/Program Files/Microsoft VS Code/bin` folder is in the `PATH`.

>     * Are you using WSL2?
Yes. At startup, Docker Desktop displaying sonething like "starting WSL 2 backend".

```
$ wsl --list -v
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  docker-desktop         Stopped         2
  docker-desktop-data    Stopped         2
```

> 
>     * Can you tell me if the following registry key `SOFTWARE\Classes\VSCodeSourceFile\shell\open`  is located in `HKEY_LOCAL_MACHINE` or `HKEY_USERS`/`HKEY_CURRENT_USER`?
`HKEY_USERS` does not have a `SOFTWARE` folder. You can find all the values from my registry :
```
$ REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VSCodeSourceFile\shell\open"

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VSCodeSourceFile\shell\open
    (par défaut)    REG_SZ    "C:\Program Files\Microsoft VS Code\Code.exe"

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VSCodeSourceFile\shell\open\command

$ REG QUERY "HKEY_USERS\SOFTWARE\Classes\VSCodeSourceFile\shell\open"""""""""
Erreur : Erreur : le système n’a pas trouvé la clé ou la valeur de Registre spécifiée.

$ REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Classes\VSCodeSourceFile\shell\open"
Erreur : Erreur : le système n’a pas trouvé la clé ou la valeur de Registre spécifiée.

$ REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Classes\vscode\shell\open"""""""""""

HKEY_CURRENT_USER\SOFTWARE\Classes\vscode\shell\open\command
sebastien@sorin:~ $ REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Classes\vscode\shell\open\command"

HKEY_CURRENT_USER\SOFTWARE\Classes\vscode\shell\open\command
    (par défaut)    REG_SZ    "C:\Program Files\Microsoft VS Code\Code.exe" --open-url -- "%1"
```

**Comment by rwood112** [comment]
> Did you add the`code` [command line](https://code.visualstudio.com/docs/editor/command-line) in your Path?

Didn't see an entry in the Path variable, but the command line produces version output:
```
C:\Users\rwood>code --version
1.57.1
507ce72a4466fbb27b715c3722558bb15afa9f48
x64
```
And the following command tells me where code is working from:
```
C:\Users\rwood>for %I in (code) do @echo %~$PATH:I
C:\Users\rwood\AppData\Local\Programs\Microsoft VS Code\bin\code
```

> Are you using WSL2?

Yes

> * Can you tell me if the following registry key `SOFTWARE\Classes\VSCodeSourceFile\shell\open`  is located in `HKEY_LOCAL_MACHINE` or `HKEY_USERS`/`HKEY_CURRENT_USER`?

```
PS C:\Users\rwood> REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VSCodeSourceFile\shell\open"
ERROR: The system was unable to find the specified registry key or value.
PS C:\Users\rwood> REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Classes\VSCodeSourceFile\shell\open"

HKEY_CURRENT_USER\SOFTWARE\Classes\VSCodeSourceFile\shell\open
    (Default)    REG_SZ    "C:\Users\rwood\AppData\Local\Programs\Microsoft VS Code\Code.exe"

HKEY_CURRENT_USER\SOFTWARE\Classes\VSCodeSourceFile\shell\open\command
```
Looks like it's in HKEY_CURRENT_USER for me.

**Comment by EdenBW** [comment]
For me only Git isn't being detected.
This is on a completely fresh win10 install.

Registry key is in HKEY_LOCAL_MACHINE
```
PS C:\Users\edenw>  REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VSCodeSourceFile\shell\open"

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VSCodeSourceFile\shell\open
    (Default)    REG_SZ    "C:\Program Files\Microsoft VS Code\Code.exe"

HKEY_LOCAL_MACHINE\SOFTWARE\Classes\VSCodeSourceFile\shell\open\command
PS C:\Users\edenw> REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Classes\VSCodeSourceFile\shell\open"
ERROR: The system was unable to find the specified registry key or value.
PS C:\Users\edenw> REG QUERY "HKEY_USERS\SOFTWARE\Classes\VSCodeSourceFile\shell\open"
ERROR: The system was unable to find the specified registry key or value.
```

Code directory in path
```
C:\Users\edenw>for %i in (code) do @echo %~$PATH:i
C:\Program Files\Microsoft VS Code\bin\code
```

Using wsl 2
```
C:\Users\edenw>wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
```

Diagnost ID: A968B590-F309-48D4-8747-C2CAC979EE8D/20210629101537

**Comment by fabioqcorreia** [comment]
Same issue here.
ID: 9B87D860-3F47-439A-A60A-FA854B4233EB/20210704134356

**Comment by LorenzoTinfena** [comment]
Same issue, It does't detect git, (fresh windows 10)

**Comment by glours** [comment]
When Git isn't detected, can you reinstall it and choose between `Git from the command line...` or `Use Git and optional Unix tools...`

<img width="369" alt="gitbash" src="https://user-images.githubusercontent.com/705411/125802766-f893c147-dd3b-4293-9cc6-00b31c5e0f01.PNG">

And if you want to clone from private repo, you also need to check the usage of the `Git Credential Manager Core`
<img width="371" alt="gitbash-credentials" src="https://user-images.githubusercontent.com/705411/125802918-e0765a0b-69b1-44e4-adff-a5505a35379b.PNG">

**Comment by rwood112** [comment]
Unfortunately, I can no longer contribute to the diagnosis of the issue. I migrated to a new machine cloning the original via a full image backup. On starting up docker desktop at that point, all the components were detected, and I was able to establish a dev environment.

**Comment by fabioqcorreia** [comment]
@glours actually not in this scope anymore, 
I'm using Windows 11 Beta channel for Insiders. 
Still Docker doesn't find any of my installed tools either and shows me a new info: 
![image](https://user-images.githubusercontent.com/16759330/129295245-815d8b46-cb1e-4aab-8de7-380a443ede21.png)

Will try following the guideline.

**Comment by LorenzoTinfena** [comment]
> @slecache @mikaelkaron @EdenBW @fabioqcorreia @LorenzoTinfena we just released the `3.6.0` version of Docker Desktop, can you check if this issue is fixed for you?
> For those who had issue in GIT detection, please follow [this guideline](https://github.com/docker/dev-environments/issues/37#issuecomment-897447168) before testing

For me it works a few days later the comment, without any changes, don't know why

**Comment by slecache** [comment]
Thank you for your patience.

Since I updated Docker Desktop, as soon as I'm in the "Dev Environments" tab, VSCode regularly opens a cli.js file.

PS: I do not have this behavior on another PC.

**Comment by glours** [comment]
Hello here

We released the version `4.2.0` of Docker Desktop last week and we added the capability to use directly Git Bash without any special configuration.

Can someone let me know if this fix this issue and if we can close it?

**Comment by slecache** [comment]
It still works but I still have the strange behavior with VSCode (see my previous comment).

**Comment by shyagamzo** [comment]
The VSCode extension is not recognized for me.

Diag. ID: FA0A526B-5CB0-48F3-B6EF-849DB959D052/20211209095751

![image](https://user-images.githubusercontent.com/95415447/145375930-3f39f39f-8e4a-417a-bf23-1f0f0d09614e.png)

![image](https://user-images.githubusercontent.com/95415447/145375693-d5f93517-5d2b-40a7-88de-8ef36fca7786.png)

Also, there's a strange behavior... When I click the 'Retry' button, VSCode opens in Restricted Mode over some internal VSCode file:
![image](https://user-images.githubusercontent.com/95415447/145376281-f79d2175-a235-4fe4-b9f7-f7d774c7e7d2.png)

**Comment by wxw-matt** [comment]
# Git is not detected
> which git
/usr/bin/git
> git --version
git version 2.30.1 (Apple Git-130)
System: macOS Monterey

![image](https://user-images.githubusercontent.com/55307382/145569973-60af2872-095b-4dd8-a9b1-f412074505c9.png)

![image](https://user-images.githubusercontent.com/55307382/145569708-561cc29e-84f0-4c80-87c8-55e930a0f8b0.png)

**Comment by glours** [comment]
@wxw-matt did you try the `retry` button? Was git installed before your first try of using Dev Env? If not try to close and reopen Docker Desktop

**Comment by wxw-matt** [comment]
@glours Thanks for your reply.
I quit Docker Desktop and retried, same result.
And the git is coming with macOS, it has been in the system before the installation of Docker.

**Comment by wxw-matt** [comment]
Fixed, need to allow Docker to access `Documents` Folder.
It seems not related between `/usr/bin/` and `Documents`.

![image](https://user-images.githubusercontent.com/55307382/145574184-1667dc58-1474-422e-a5be-1fa2681b0cc0.png)
