### ISSUE TITLE
Unable to clone repository from path that includes spaces

### ISSUE THREAD

**Issue by BennB** [docker/dev-environments#68]
I would like to create an environment using a repository from Azure Repos. When I provide a Repository URL and click the create button for the 'Create a Dev Environment' dialog I get an error stating the volume name is invalid.

**Steps to Reproduce:**
1. Copy the Azure repository clone link. i.e. https://corpname.visualstudio.com/DefaultCollection/IT%20Projects/_git/IT%20Projects
2. From Docker Desktop go to Dev Environments.
3. Click on the create button in top right hand corner, the 'Create a Dev Environment' dialog will display.
4. Paste the copied clone link (from step 1) into the Repository URL text box provided in the dialog.
3. Click the create button.
4. An error appears "Error response from daemon: create volume-IT%20Projectsn-goofy_lichterman: "volume-IT%20Projectsn-goofy_lichterman" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path"

**Expected behavior**
A successfully created container.

**Desktop (please complete the following information):**
 - OS: Windows 10 Business

**Version of Docker Desktop:**  
You can find the version by clicking on the `About Docker Desktop` menu
```
![image](https://user-images.githubusercontent.com/229036/135027807-c6d213ed-9065-46ee-a121-a3d8e430ee24.png)


```

**Comment by felipecruz91** [comment]
Hey @BennB,

Thank you for taking the time to report the issue. I've been able to replicate it and we'll add it to our internal backlog. We'll let you know when we have an update.

**Comment by glours** [comment]
Hello @BennB,

We released a new version of Docker Desktop `4.2.0` last week which should fix this issue.
Can you update to this release and check everything is working as expected?

**Comment by BennB** [comment]
Hi Guillaume,

Thank you for you message. I just tried cloning a dev ops repository,
unfortunately still get the same invalid characters error.
I wanted to add that our repository name has a space in it, which is
encoded as %20 in the url.

e.g.
<repository url>/_git/My%20Repository

See below images for details.

Kind regards
Benn

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by glours** [comment]
@BennB 

A new release of Docker Desktop `4.4.1 ` just landed and should fix your issue. Can you give it a try and let me know if we can close the issue?

**Comment by BennB** [comment]
Hi Guillaume,

It appears to be working now. Thank you.

Kind Regards,
Benn
