### ISSUE TITLE
Unable to start or remove a environment with a space

### ISSUE THREAD

**Issue by rvhelden** [docker/dev-environments#69]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Actual behavior
When cloning a repository with the dev enviroment feature with a space in the name, then the workspace becomes unusable.
Unable to start the enviroment and unable to remove the enviroment, but it is created and completely stuck, unable to run it or remove it

### Expected behavior
Be able to start and remove the environment as anyother environment

### Information
  - Is it reproducible? Yes, Clone a git repository with a space in the name, the spaces gets translated to %20
  - Is the problem new? Yes
  - Did the problem appear with an update? With the feature
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
 
  - Windows Version: Windows 10 21H1
  - Docker Desktop Version: Latest
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior
Clone a git repository with a space in the name, the spaces gets translated to %20
Then you cannot delete the environment or start the environment. It is completely stuck

**Comment by felipecruz91** [comment]
@rvhelden This is fixed in Docker Desktop `4.3.0`. Could you try again?

**Comment by rvhelden** [comment]
@felipecruz91 No the issue is still present

![image](https://user-images.githubusercontent.com/4113326/144583268-45057c55-16f5-4191-a60d-d76a24d77b28.png)
![image](https://user-images.githubusercontent.com/4113326/144583330-df881e4d-aac5-402d-beab-d34e89d773cb.png)
![image](https://user-images.githubusercontent.com/4113326/144583349-baf1d580-6f74-4052-9aa5-58b42ac7ae5f.png)

**Comment by felipecruz91** [comment]
@rvhelden Could you clean up any past Dev Environments? You'll have to delete them from `C:\Users\<your user>\.docker\devenvironments\data.json` and also the associated directories.

I'd like you to retry from scratch and let us know if the problem is still present.

**Comment by rvhelden** [comment]
@felipecruz91 Thanks that works 👍
